services:
  package-db:
    image: postgres:16.1
    container_name: packages-service-db
    ports:
      - "6432:5432"
    environment:
      - POSTGRES_DB=packages
      - POSTGRES_USER=packages
      - POSTGRES_PASSWORD=packages
