spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:6432/packages
    username: packages
    password: packages
  sql:
    init:
      mode: always
  main:
    banner-mode: off
    web-application-type: none

#logging:
  #pattern:
   # console: