spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:6432/alt_test_db
    username: altuser
    password: altpassword
  sql:
    init:
      mode: always
  main:
    banner-mode: off
    web-application-type: none

logging:
  pattern:
    console: